name: Build Project (Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Solution Compilation
      run: dotnet build --configuration Debug "templatepack.sln"
    - uses: actions/upload-artifact@v3
      if: success()
      with:
        name: grilo-build
        path: "working/bin/Debug/"
        
