name: NuGet Gallery Push

on:
  release:
    types: [published]
    
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Solution Compilation
      run: dotnet pack templatepack.sln /p:Configuration=Release
    - name: NuGet Preparation
      run: nuget setApiKey ${{ secrets.NUGET_APIKEY }}
    - name: Package Publication (Boot)
      run: |
        $path = "working\bin\Release"
        $FileName = Get-ChildItem -Path $path -Name -Filter "KS.Templates.*"
        nuget push "$path\$FileName" -source "nuget.org" -SkipDuplicate
        
